language: python
python:
  - "3.5"
# command to install dependencies
before_script:
  - cd $TRAVIS_BUILD_DIR/api
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script:
  - nosetests --with-coverage
branches:
  only:
  - ft-api-endpoints
after_success:
  - coveralls
ignore:
  - venv/*
  - ctypes/*
  - html/*
  - crypt.py
  - decimal.py
  - encodings
  - hmac.py
  - mimetypes.py
  - stringprep.py
  - uuid.py
  - http/*
  - numbers.py
  - click/*
  - flask/*
  - itsdangerous.py
  - jinja2/*
  - markupsafe/*
  - werkzeug/*
