language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script:
  - nosetests --with-coverage
branches:
  only:
  - ft-database
after_success:
  - coveralls
