language: python
python:
  - "3.5"
services:
  - postgresql
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
  - python app.py migrate --noinput
script:
  - python app.py test --keepdb
  - nosetests --with-coverage
branches:
  only:
  - ft-database
after_success:
  - coveralls
env:
  - DB=postgres
