"""empty message

Revision ID: 859b56bcdc32
Revises: 2a9761279c4c
Create Date: 2018-05-15 21:37:12.274030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859b56bcdc32'
down_revision = '2a9761279c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authtokens')
    # ### end Alembic commands ###
